# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Multi-provider CLI for Jira, Tempo, and more"
  homepage "https://github.com/josefdolezal/g"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/g/releases/download/v0.1.0/g_0.1.0_darwin_amd64.tar.gz"
      sha256 "f69ae96f2ad7e6450516b19adb8357f235c06b387396e9aef641e88282e8a527"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/g/releases/download/v0.1.0/g_0.1.0_darwin_arm64.tar.gz"
      sha256 "df24403c59cb7cc154610514a01dcf5f0d4428c11f9e98bf5780829424f26e85"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.1.0/g_0.1.0_linux_amd64.tar.gz"
      sha256 "26e17f50a8b2c359e781957c7ba181c212c18aedf2175ee964d5cb979b509493"
      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.1.0/g_0.1.0_linux_arm64.tar.gz"
      sha256 "7553b021e46371d66cb2f2919e492c1120f4c6ed2c571beb62b99f7a2af9eeaa"
      def install
        bin.install "g"
      end
    end
  end

  test do
    system "#{bin}/g", "--version"
  end
end
