# This file was generated by GoReleaser. DO NOT EDIT.
cask "g" do
  name "g"
  desc "Multi-provider CLI for Jira, Tempo, and more"
  homepage "https://github.com/josefdolezal/g"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "g"

  on_macos do
    on_intel do
      url "https://github.com/josefdolezal/g/releases/download/v#{version}/g_#{version}_darwin_amd64.tar.gz"
      sha256 "d5b39894cab84532ca0ec827bcd39f811a3862f54af43e03e302ebda59930bd4"
    end
    on_arm do
      url "https://github.com/josefdolezal/g/releases/download/v#{version}/g_#{version}_darwin_arm64.tar.gz"
      sha256 "df66c356b6c5f6e4dcf55b09fa36a62e112f31ec48428b4509636b4ff54fb363"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/josefdolezal/g/releases/download/v#{version}/g_#{version}_linux_amd64.tar.gz"
      sha256 "9d496bbf013744de4cef2a2f7cd75d4893a545dd1c514422563a6eba616a27c6"
    end
    on_arm do
      url "https://github.com/josefdolezal/g/releases/download/v#{version}/g_#{version}_linux_arm64.tar.gz"
      sha256 "5cd78b1effcae3650268bc779529d2cef7cd1a83703fcd003a624fa76ac8af70"
    end
  end

  # No zap stanza required
end
