# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Multi-provider CLI for Jira, Tempo, and more"
  homepage "https://github.com/josefdolezal/g"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/g/releases/download/v0.2.0/g_0.2.0_darwin_amd64.tar.gz"
      sha256 "c6eb60a76e8b4ce6990a4bab3f3b0266fd33bc32e7b5b4fc6caa2ef84cd445d5"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/g/releases/download/v0.2.0/g_0.2.0_darwin_arm64.tar.gz"
      sha256 "af028739db2342c49aa942e5d2cd2a4dab412448b57e14d154cf30c5caa4a16e"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.2.0/g_0.2.0_linux_amd64.tar.gz"
      sha256 "a2568eb2ebacc118820e265b245cf3781de59333bf1f17b2dcae16df9705447c"
      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.2.0/g_0.2.0_linux_arm64.tar.gz"
      sha256 "73c6c724a93b276fe8be486038fb096642dab6689d74e8624e22029fe810a138"
      def install
        bin.install "g"
      end
    end
  end

  test do
    system "#{bin}/g", "--version"
  end
end
