# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appctl < Formula
  desc "JSON-first CLI for iOS Simulators and Android devices"
  homepage "https://github.com/josefdolezal/appctl"
  version "0.0.2"

  depends_on "facebook/fb/idb-companion" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.2/appctl_0.0.2_darwin_amd64.tar.gz"
      sha256 "4e65330ae720c04f2f656255cbac259e25786ea6d8ce915dbe147dda54838349"

      define_method(:install) do
        bin.install "appctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.2/appctl_0.0.2_darwin_arm64.tar.gz"
      sha256 "6aab43df7b1f43c0fb7112d6519dda1d7e7b01df6d463771f699969b8d9a70e9"

      define_method(:install) do
        bin.install "appctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.2/appctl_0.0.2_linux_amd64.tar.gz"
      sha256 "5a65e0b5a0e87192b7bd63d4ccb50b5c19519a1608307338c26e3e0c0585b8c8"
      define_method(:install) do
        bin.install "appctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.2/appctl_0.0.2_linux_arm64.tar.gz"
      sha256 "26cce8125b2b649581f77439470cf6857e0675df28d166be69627fb12705f444"
      define_method(:install) do
        bin.install "appctl"
      end
    end
  end

  def caveats
    <<~EOS
      appctl auto-installs facebook/fb/idb-companion on macOS.

      Install the remaining runtime tools manually:
        brew install --cask android-platform-tools
        python3 -m pip install fb-idb

      iOS simulator support also requires Xcode or Xcode Command Line Tools for xcrun simctl.
    EOS
  end

  test do
    system "#{bin}/appctl", "--version"
  end
end
