# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appctl < Formula
  desc "JSON-first CLI for iOS Simulators and Android devices"
  homepage "https://github.com/josefdolezal/appctl"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.1/appctl_0.0.1_darwin_amd64.tar.gz"
      sha256 "f6a364d364a895d334857ab7e57b2886c31beeb12318294ed20d16f8e6db8908"

      define_method(:install) do
        bin.install "appctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.1/appctl_0.0.1_darwin_arm64.tar.gz"
      sha256 "232d9af0c9f8a29d47a311091c51a510d1170e900c72af7072bcc71c5fc8ca85"

      define_method(:install) do
        bin.install "appctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.1/appctl_0.0.1_linux_amd64.tar.gz"
      sha256 "231b4ce5d81f88ed4c5f749e4839e3d38b37089dc325e4ef8a1df474e34d3874"
      define_method(:install) do
        bin.install "appctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/appctl/releases/download/v0.0.1/appctl_0.0.1_linux_arm64.tar.gz"
      sha256 "993588a7c97080ac2ab9d155a5b4de406a275b95d831b32486b3883dbc6661b3"
      define_method(:install) do
        bin.install "appctl"
      end
    end
  end

  test do
    system "#{bin}/appctl", "--version"
  end
end
