# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crew < Formula
  desc "Orchestrate interactive coding-agent sessions (Claude Code, Codex, pi) in tmux"
  homepage "https://github.com/josefdolezal/crew"
  version "0.2.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/crew/releases/download/v0.2.1/crew_0.2.1_darwin_amd64.tar.gz"
      sha256 "587af79741ef7df0db14f82e768d8501f8a9a882e5964da588bf978c7b6bbd3a"

      define_method(:install) do
        bin.install "crew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/crew/releases/download/v0.2.1/crew_0.2.1_darwin_arm64.tar.gz"
      sha256 "6a0525c208d5b2654ac6dc300394232bcfd2eabb741b8b472b6da4006ff0cddc"

      define_method(:install) do
        bin.install "crew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/crew/releases/download/v0.2.1/crew_0.2.1_linux_amd64.tar.gz"
      sha256 "96fc1b7be2abccdc686c1df148a49acb0315591952b029d7e1a51f4b010e969b"
      define_method(:install) do
        bin.install "crew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/crew/releases/download/v0.2.1/crew_0.2.1_linux_arm64.tar.gz"
      sha256 "270af5477b0e3e2f59e944773891f1c9a064973125b8218474651909a162179c"
      define_method(:install) do
        bin.install "crew"
      end
    end
  end

  test do
    system "#{bin}/crew", "--version"
  end
end
