# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Multi-provider CLI for Jira, Tempo, and more"
  homepage "https://github.com/josefdolezal/g"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/g/releases/download/v0.3.0/g_0.3.0_darwin_amd64.tar.gz"
      sha256 "f6c93839d36fd0363c357c92dbb774a9eb2bf7a2d26b6669c22adc9d5f54d47b"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/g/releases/download/v0.3.0/g_0.3.0_darwin_arm64.tar.gz"
      sha256 "820de2761bd068962d864d82b87d2633b1b8a5f352cb3c7530e577d3e56ac318"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.3.0/g_0.3.0_linux_amd64.tar.gz"
      sha256 "2fc12ca5c2bc69afd42d5a40370fe6dc29b239fb5266367182533a78539debb8"
      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.3.0/g_0.3.0_linux_arm64.tar.gz"
      sha256 "bd83ecb28ee8adf64663ae449ecbe1e629edac8fefad621986df33eb6e2ac236"
      def install
        bin.install "g"
      end
    end
  end

  test do
    system "#{bin}/g", "--version"
  end
end
