# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Multi-provider CLI for Jira, Tempo, and more"
  homepage "https://github.com/josefdolezal/g"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/g/releases/download/v0.4.0/g_0.4.0_darwin_amd64.tar.gz"
      sha256 "991e079aa6d52b41b580cf9849a679609bdf729c04f924f84278788b47577630"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/g/releases/download/v0.4.0/g_0.4.0_darwin_arm64.tar.gz"
      sha256 "00f2ad910c9cc6b8321612378dd5c9d782e53fc947c43d5abdc49399f57e0e60"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.4.0/g_0.4.0_linux_amd64.tar.gz"
      sha256 "c14687cf40f907eb0da58e2111e732e3f35bcdd07c7e1737692a4787a74ee02c"
      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/g/releases/download/v0.4.0/g_0.4.0_linux_arm64.tar.gz"
      sha256 "59d09a4e3277d6b0e5586113ebddde5d8f307180206aaf377d47711177df6fce"
      def install
        bin.install "g"
      end
    end
  end

  test do
    system "#{bin}/g", "--version"
  end
end
