# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unpkgo < Formula
  desc "Download, inspect, decrypt, and extract PlayStation PKG files"
  homepage "https://github.com/josefdolezal/unPKGo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josefdolezal/unPKGo/releases/download/v0.1.0/unpkgo_0.1.0_darwin_amd64.tar.gz"
      sha256 "489144e9d4727e102c12d15b4763f506f2846aff062530d8def6760f969822b4"

      define_method(:install) do
        bin.install "unpkgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josefdolezal/unPKGo/releases/download/v0.1.0/unpkgo_0.1.0_darwin_arm64.tar.gz"
      sha256 "da4711e8bdb7bc56743678d2b7d0db2c1e8c36da180469f49c87abbbf3e7fb8e"

      define_method(:install) do
        bin.install "unpkgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/unPKGo/releases/download/v0.1.0/unpkgo_0.1.0_linux_amd64.tar.gz"
      sha256 "47f72d6f84c02d042f4b17947eabc670aab78c7d36ac379f0f5d52ac095e2e9f"
      define_method(:install) do
        bin.install "unpkgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josefdolezal/unPKGo/releases/download/v0.1.0/unpkgo_0.1.0_linux_arm64.tar.gz"
      sha256 "0de41902593078ce614081931ce428c62e4172894fddb67235f4e1a71eefadae"
      define_method(:install) do
        bin.install "unpkgo"
      end
    end
  end

  test do
    system "#{bin}/unpkgo", "--version"
  end
end
